import Head from "next/head";
// import Image from "next/image";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Product from "../components/Product";

export default function Home() {
  //Fetch the data from the graphql endpoint
  const [result] = useQuery({ query: PRODUCT_QUERY });
  // console.log(result);
  const { data, fetching, error } = result;

  if (fetching) {
    return <p>Loading...</p>;
  }

  if (error) {
    return <p> Error Recieved...{error.message}</p>;
  }

  const products = data.products.data;

  console.log(products);

  return (
    <div>
      <Head>
        <title>My E-Commerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {/* {products.map((product) => (
          <h1>{product.attributes.title}</h1>
        ))} */}
        {products.map((product) => (
          <Product key={product.attributes.slug} product={product} />
        ))}
      </main>
    </div>
  );
}
